name: lm_flutter
description: Flutter Application for Lastminute

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  connectivity: ^0.4.2
  device_info: ^0.4.0+1
  package_info: ^0.4.0+2
  dio: ^2.1.0
  json_annotation: ^2.0.0
  fluttertoast: ^3.0.1
  cached_network_image: ^0.8.0
  carousel_slider: ^1.3.0

  font_awesome_flutter: ^8.4.0
  community_material_icon: 2.8.94

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/images/
